'use strict';

const REACT_ROOT_EXTERNAL = 'React';

const REACT_DOM_ROOT_EXTERNAL = 'ReactDom';

const REACT_CSS_TRANSITION_GROUP_ROOT_EXTERNAL = 'ReactAddonsCssTransitionGroup';

const REDUX_ROOT_EXTERNAL = 'Redux';

const REACT_REDUX_ROOT_EXTERNAL = 'ReactRedux';

const VUE_ROOT_EXTERNAL = 'Vue';

const VUEX_ROOT_EXTERNAL = 'Vuex';

module.exports = {
    REACT_ROOT_EXTERNAL,
    REACT_DOM_ROOT_EXTERNAL,
    REACT_CSS_TRANSITION_GROUP_ROOT_EXTERNAL,
    REDUX_ROOT_EXTERNAL,
    REACT_REDUX_ROOT_EXTERNAL,
    VUE_ROOT_EXTERNAL,
    VUEX_ROOT_EXTERNAL
};
